default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dbc-thanks_development

test:
  <<: *default
  database: dbc-thanks_test

production:
  <<: *default
  database: ENV["DATABASE_URL"]
